export interface PlanetData {
  name: string;
  orbitRadius: number; // px from sun center for display
  period: number; // animation duration in seconds
  size: number; // display diameter in px
  color: string;
  gradient: string; // CSS radial-gradient for realistic look
  image: string; // path to planet photo in /public/planets/
  gallery: string[]; // 5 gallery images for detail view
  ringColor?: string;
  distanceAU: number;
  diameterKm: number;
  moons: number;
  dayLength: string;
  yearLength: string;
  avgTemp: string;
  description: string;
}

export const SUN: PlanetData = {
  name: "Sun",
  orbitRadius: 0,
  period: 0,
  size: 64,
  color: "#ffd700",
  gradient: "radial-gradient(circle at 35% 35%, #fff8dc 0%, #ffd700 30%, #ff8c00 60%, #cc6600 100%)",
  image: "/planets/sun.webp",
  gallery: [
    "/planets/gallery/sun-1.webp",
    "/planets/gallery/sun-2.webp",
    "/planets/gallery/sun-4.webp",
    "/planets/gallery/sun-3.webp",
    "/planets/gallery/sun-5.webp",
  ],
  distanceAU: 0,
  diameterKm: 1392700,
  moons: 0,
  dayLength: "25.4 Earth days",
  yearLength: "N/A",
  avgTemp: "5,500 C (surface)",
  description: "The star at the centre of our solar system. A nearly perfect sphere of hot plasma, the Sun provides the energy that sustains life on Earth. It contains 99.86% of the total mass of the solar system.",
};

export const PLANETS: PlanetData[] = [
  {
    name: "Mercury",
    orbitRadius: 80,
    period: 12,
    size: 8,
    color: "#8c7853",
    gradient: "radial-gradient(circle at 35% 35%, #c2b09a 0%, #8c7853 40%, #5a4d3a 70%, #3a3228 100%)",
    image: "/planets/mercury.webp",
    gallery: [
      "/planets/gallery/mercury-1.webp",
      "/planets/gallery/mercury-4.webp",
      "/planets/gallery/mercury-5.webp",
      "/planets/gallery/mercury-2.webp",
      "/planets/gallery/mercury-3.webp",
    ],
    distanceAU: 0.39,
    diameterKm: 4879,
    moons: 0,
    dayLength: "59 Earth days",
    yearLength: "88 Earth days",
    avgTemp: "167 C",
    description: "The smallest planet and closest to the Sun. Mercury has virtually no atmosphere and experiences extreme temperature swings.",
  },
  {
    name: "Venus",
    orbitRadius: 120,
    period: 18,
    size: 14,
    color: "#e6c87a",
    gradient: "radial-gradient(circle at 35% 35%, #f5e6c8 0%, #e6c87a 35%, #c49a4a 60%, #8a6a2e 100%)",
    image: "/planets/venus.webp",
    gallery: [
      "/planets/gallery/venus-1.webp",
      "/planets/gallery/venus-2.webp",
      "/planets/gallery/venus-3.webp",
      "/planets/gallery/venus-4.webp",
      "/planets/gallery/venus-5.webp",
    ],
    distanceAU: 0.72,
    diameterKm: 12104,
    moons: 0,
    dayLength: "243 Earth days",
    yearLength: "225 Earth days",
    avgTemp: "464 C",
    description: "Often called Earth's twin due to similar size. Venus has a thick, toxic atmosphere that traps heat in a runaway greenhouse effect.",
  },
  {
    name: "Earth",
    orbitRadius: 170,
    period: 24,
    size: 14,
    color: "#4a90e2",
    gradient: "radial-gradient(circle at 35% 35%, #8cc5f0 0%, #4a90e2 30%, #2e6b3e 50%, #1a5c2a 65%, #1b4a7a 80%, #0d2847 100%)",
    image: "/planets/earth.webp",
    gallery: [
      "/planets/gallery/earth-1.webp",
      "/planets/gallery/earth-3.webp",
      "/planets/gallery/earth-5.webp",
      "/planets/gallery/earth-2.webp",
      "/planets/gallery/earth-4.webp",
    ],
    distanceAU: 1.0,
    diameterKm: 12756,
    moons: 1,
    dayLength: "24 hours",
    yearLength: "365.25 days",
    avgTemp: "15 C",
    description: "Our home world. The only planet known to harbor life, with liquid water covering about 71% of its surface.",
  },
  {
    name: "Mars",
    orbitRadius: 220,
    period: 32,
    size: 10,
    color: "#d45a43",
    gradient: "radial-gradient(circle at 35% 35%, #e8845a 0%, #d45a43 35%, #a8432e 55%, #7a2e1e 80%, #4a1a10 100%)",
    image: "/planets/mars.webp",
    gallery: [
      "/planets/gallery/mars-1.webp",
      "/planets/gallery/mars-2.webp",
      "/planets/gallery/mars-3.webp",
      "/planets/gallery/mars-4.webp",
      "/planets/gallery/mars-5.webp",
    ],
    distanceAU: 1.52,
    diameterKm: 6792,
    moons: 2,
    dayLength: "24.6 hours",
    yearLength: "687 Earth days",
    avgTemp: "-65 C",
    description: "The Red Planet. Mars is a cold desert world with a thin atmosphere. Multiple rovers and orbiters actively study its surface.",
  },
  {
    name: "Jupiter",
    orbitRadius: 310,
    period: 48,
    size: 32,
    color: "#c88b3a",
    gradient: "radial-gradient(circle at 35% 35%, #e8c88a 0%, #c88b3a 25%, #b07830 40%, #a06828 50%, #d4a050 55%, #b07830 60%, #8a5a20 75%, #5a3a10 100%)",
    image: "/planets/jupiter.webp",
    gallery: [
      "/planets/gallery/jupiter-1.webp",
      "/planets/gallery/jupiter-3.webp",
      "/planets/gallery/jupiter-5.webp",
      "/planets/gallery/jupiter-2.webp",
      "/planets/gallery/jupiter-4.webp",
    ],
    distanceAU: 5.2,
    diameterKm: 142984,
    moons: 95,
    dayLength: "9.9 hours",
    yearLength: "11.9 Earth years",
    avgTemp: "-110 C",
    description: "The largest planet in our solar system. Jupiter's Great Red Spot is a storm larger than Earth that has raged for centuries.",
  },
  {
    name: "Saturn",
    orbitRadius: 400,
    period: 64,
    size: 26,
    color: "#f4d47c",
    gradient: "radial-gradient(circle at 35% 35%, #faecc8 0%, #f4d47c 30%, #d4b46c 50%, #c4a45c 65%, #a08040 85%, #6a5428 100%)",
    image: "/planets/saturn.webp",
    gallery: [
      "/planets/gallery/saturn-1.webp",
      "/planets/gallery/saturn-3.webp",
      "/planets/gallery/saturn-5.webp",
      "/planets/gallery/saturn-2.webp",
      "/planets/gallery/saturn-4.webp",
    ],
    ringColor: "rgba(244, 212, 124, 0.3)",
    distanceAU: 9.58,
    diameterKm: 120536,
    moons: 146,
    dayLength: "10.7 hours",
    yearLength: "29.5 Earth years",
    avgTemp: "-140 C",
    description: "Famous for its stunning ring system made of ice and rock. Saturn is a gas giant with at least 146 known moons.",
  },
  {
    name: "Uranus",
    orbitRadius: 480,
    period: 84,
    size: 20,
    color: "#72c5d0",
    gradient: "radial-gradient(circle at 35% 35%, #a8e8f0 0%, #72c5d0 35%, #5aacb8 55%, #4a98a5 70%, #2a6878 90%, #1a4858 100%)",
    image: "/planets/uranus.webp",
    gallery: [
      "/planets/gallery/uranus-1.webp",
      "/planets/gallery/uranus-4.webp",
      "/planets/gallery/uranus-5.webp",
      "/planets/gallery/uranus-2.webp",
      "/planets/gallery/uranus-3.webp",
    ],
    ringColor: "rgba(114, 197, 208, 0.2)",
    distanceAU: 19.22,
    diameterKm: 51118,
    moons: 28,
    dayLength: "17.2 hours",
    yearLength: "84 Earth years",
    avgTemp: "-195 C",
    description: "An ice giant that rotates on its side. Uranus has a pale blue-green color from methane in its atmosphere.",
  },
  {
    name: "Neptune",
    orbitRadius: 550,
    period: 100,
    size: 18,
    color: "#3b5eab",
    gradient: "radial-gradient(circle at 35% 35%, #6b8ed4 0%, #3b5eab 35%, #2e4a8a 55%, #1e3a7a 70%, #142a5a 90%, #0a1a3a 100%)",
    image: "/planets/neptune.webp",
    gallery: [
      "/planets/gallery/neptune-1.webp",
      "/planets/gallery/neptune-3.webp",
      "/planets/gallery/neptune-4.webp",
      "/planets/gallery/neptune-2.webp",
      "/planets/gallery/neptune-5.webp",
    ],
    distanceAU: 30.05,
    diameterKm: 49528,
    moons: 16,
    dayLength: "16.1 hours",
    yearLength: "165 Earth years",
    avgTemp: "-200 C",
    description: "The most distant planet from the Sun. Neptune has the fastest winds in the solar system, exceeding 2,000 km/h.",
  },
];
